### ISSUE TITLE
Monitor config files for changes and update tests

### ISSUE THREAD

**Issue by rossknudsen** [kavod-io/vscode-jest-test-adapter#20]
- [ ] Added config files should cause additional tests to be found.  This probably depends on #9 being implemented first.  In the meantime, we should invalidate all tests.
- [ ] Removed config files should cause tests to be removed.  This probably depends on #9 being implemented first.  In the meantime, we should invalidate all tests.
- [ ] Modified config files should cause tests to be updated.  This probably depends on #9 being implemented first.  In the meantime, we should invalidate all tests.
